<?php
/** @var Magento\Framework\View\Element\Template $block */
?>
<div class="blog-post-sidebar">
    <p><strong><?= __('Other blog posts') ?></strong></p>
    <ul>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 1]) ?>">Post 1</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 2]) ?>">Post 2</a></li>
        <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => 3]) ?>">Post 3</a></li>
    </ul>
</div>
